"Make a symbolic link from this file to your .vimrc

"Install vim-plug
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

map <C-p> :w<CR>:! ./%<CR>

" Specify a directory for plugins
" - For Neovim: stdpath('data') . '/plugged'
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin()

" Plugin outside ~/.vim/plugged with post-update hook
Plug 'junegunn/fzf.vim'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all', 'frozen': 1 }
Plug 'tpope/vim-commentary'
Plug 'nathanaelkane/vim-indent-guides'

" Initialize plugin system
call plug#end()

let g:mapleader=" "

function! GitZF(...)
	let committed = 'git diff-tree --relative --no-commit-id --name-status -r master.. | awk ''{ print $NF }'''
	let current = 'git status --short | awk ''{ print $NF }'''
	let dedup = 'awk ''!x[$1]++'''
	let cmd = 'echo "$(' . committed . ')\n$(' . current . ')" |' . dedup
	call fzf#run({
		\ 'source': cmd,
		\ 'sink': 'e',
		\ 'options': '--multi --preview "bat --style=numbers --color=always {} || highlight -O ansi -l {} || coderay {} || rougify {} || cat {}"'
	\ })
endfunction
command! GZF call GitZF()
nnoremap <Leader>g mA:GZF<CR>
nnoremap <Leader>/ mA:Ag<CR>
nnoremap <Leader><c-l> mA:call fzf#vim#buffer_lines(expand('<cword>'))<CR>
nnoremap <Leader><c-L> mA:call fzf#vim#lines(expand('<cword>'))<CR>
nnoremap <Leader>f mA:Files<CR>
nnoremap <Leader>b mA:Buffers<CR>
nnoremap <Leader>l mA:BLines<CR>
nnoremap <Leader>L mA:Lines<CR>
nnoremap <Leader>w mA:Windows<CR>

set number
set shiftwidth=2
set tabstop=2
set expandtab

set visualbell
